export const FREE_PLAN_MAX_SUBSCRIPTIONS = 10;
export const PREMIUM_PLAN_MAX_SUBSCRIPTIONS = Number.POSITIVE_INFINITY;
export const FREE_PLAN_MAX_INCLUDED_SERVICES_PER_SUBSCRIPTION = 3;
export const PREMIUM_PLAN_MAX_INCLUDED_SERVICES_PER_SUBSCRIPTION =
  Number.POSITIVE_INFINITY;
export const DEFAULT_REMINDER_DAYS_BEFORE = 3;
