export type CurrencyOption = {
  code: string;
  name: string;
};

export const ALL_CURRENCY_OPTIONS: CurrencyOption[] = [
  { code: "AED", name: "dirham des emirats arabes unis" },
  { code: "AFN", name: "afghani afghan" },
  { code: "ALL", name: "lek albanais" },
  { code: "AMD", name: "dram armenien" },
  { code: "ANG", name: "florin antillais" },
  { code: "AOA", name: "kwanza angolais" },
  { code: "ARS", name: "peso argentin" },
  { code: "AUD", name: "dollar australien" },
  { code: "AWG", name: "florin arubais" },
  { code: "AZN", name: "manat azeri" },
  { code: "BAM", name: "mark convertible bosniaque" },
  { code: "BBD", name: "dollar barbadien" },
  { code: "BDT", name: "taka bangladeshi" },
  { code: "BGN", name: "lev bulgare" },
  { code: "BHD", name: "dinar bahreini" },
  { code: "BIF", name: "franc burundais" },
  { code: "BMD", name: "dollar bermudien" },
  { code: "BND", name: "dollar bruneien" },
  { code: "BOB", name: "boliviano bolivien" },
  { code: "BRL", name: "real bresilien" },
  { code: "BSD", name: "dollar bahameen" },
  { code: "BTN", name: "ngultrum bouthanais" },
  { code: "BWP", name: "pula botswanais" },
  { code: "BYN", name: "rouble bielorusse" },
  { code: "BZD", name: "dollar belizeen" },
  { code: "CAD", name: "dollar canadien" },
  { code: "CDF", name: "franc congolais" },
  { code: "CHF", name: "franc suisse" },
  { code: "CLP", name: "peso chilien" },
  { code: "CNY", name: "yuan renminbi chinois" },
  { code: "COP", name: "peso colombien" },
  { code: "CRC", name: "colon costaricain" },
  { code: "CUC", name: "peso cubain convertible" },
  { code: "CUP", name: "peso cubain" },
  { code: "CVE", name: "escudo capverdien" },
  { code: "CZK", name: "couronne tcheque" },
  { code: "DJF", name: "franc djiboutien" },
  { code: "DKK", name: "couronne danoise" },
  { code: "DOP", name: "peso dominicain" },
  { code: "DZD", name: "dinar algerien" },
  { code: "EGP", name: "livre egyptienne" },
  { code: "ERN", name: "nafka erythreen" },
  { code: "ETB", name: "birr ethiopien" },
  { code: "EUR", name: "euro" },
  { code: "FJD", name: "dollar fidjien" },
  { code: "FKP", name: "livre des iles malouines" },
  { code: "GBP", name: "livre sterling" },
  { code: "GEL", name: "lari georgien" },
  { code: "GHS", name: "cedi ghaneen" },
  { code: "GIP", name: "livre de gibraltar" },
  { code: "GMD", name: "dalasi gambien" },
  { code: "GNF", name: "franc guineen" },
  { code: "GTQ", name: "quetzal guatemalteque" },
  { code: "GYD", name: "dollar du guyana" },
  { code: "HKD", name: "dollar de hong kong" },
  { code: "HNL", name: "lempira hondurien" },
  { code: "HRK", name: "kuna croate" },
  { code: "HTG", name: "gourde haitienne" },
  { code: "HUF", name: "forint hongrois" },
  { code: "IDR", name: "roupie indonesienne" },
  { code: "ILS", name: "nouveau shekel israelien" },
  { code: "INR", name: "roupie indienne" },
  { code: "IQD", name: "dinar irakien" },
  { code: "IRR", name: "riyal iranien" },
  { code: "ISK", name: "couronne islandaise" },
  { code: "JMD", name: "dollar jamaiquain" },
  { code: "JOD", name: "dinar jordanien" },
  { code: "JPY", name: "yen japonais" },
  { code: "KES", name: "shilling kenyan" },
  { code: "KGS", name: "som kirghize" },
  { code: "KHR", name: "riel cambodgien" },
  { code: "KMF", name: "franc comorien" },
  { code: "KPW", name: "won nord-coreen" },
  { code: "KRW", name: "won sud-coreen" },
  { code: "KWD", name: "dinar koweitien" },
  { code: "KYD", name: "dollar des iles caimans" },
  { code: "KZT", name: "tenge kazakh" },
  { code: "LAK", name: "kip laotien" },
  { code: "LBP", name: "livre libanaise" },
  { code: "LKR", name: "roupie srilankaise" },
  { code: "LRD", name: "dollar liberien" },
  { code: "LSL", name: "loti lesothan" },
  { code: "LYD", name: "dinar libyen" },
  { code: "MAD", name: "dirham marocain" },
  { code: "MDL", name: "leu moldave" },
  { code: "MGA", name: "ariary malgache" },
  { code: "MKD", name: "denar macedonien" },
  { code: "MMK", name: "kyat myanmarais" },
  { code: "MNT", name: "tugrik mongol" },
  { code: "MOP", name: "pataca macanaise" },
  { code: "MRU", name: "ouguiya mauritanien" },
  { code: "MUR", name: "roupie mauricienne" },
  { code: "MVR", name: "rufiyaa maldivienne" },
  { code: "MWK", name: "kwacha malawite" },
  { code: "MXN", name: "peso mexicain" },
  { code: "MYR", name: "ringgit malais" },
  { code: "MZN", name: "metical mozambicain" },
  { code: "NAD", name: "dollar namibien" },
  { code: "NGN", name: "naira nigerian" },
  { code: "NIO", name: "cordoba oro nicaraguayen" },
  { code: "NOK", name: "couronne norvegienne" },
  { code: "NPR", name: "roupie nepalaise" },
  { code: "NZD", name: "dollar neo-zelandais" },
  { code: "OMR", name: "riyal omanais" },
  { code: "PAB", name: "balboa panameen" },
  { code: "PEN", name: "sol peruvien" },
  { code: "PGK", name: "kina papouan-neo-guineen" },
  { code: "PHP", name: "peso philippin" },
  { code: "PKR", name: "roupie pakistanaise" },
  { code: "PLN", name: "zloty polonais" },
  { code: "PYG", name: "guarani paraguayen" },
  { code: "QAR", name: "riyal qatari" },
  { code: "RON", name: "leu roumain" },
  { code: "RSD", name: "dinar serbe" },
  { code: "RUB", name: "rouble russe" },
  { code: "RWF", name: "franc rwandais" },
  { code: "SAR", name: "riyal saoudien" },
  { code: "SBD", name: "dollar des iles salomon" },
  { code: "SCR", name: "roupie des seychelles" },
  { code: "SDG", name: "livre soudanaise" },
  { code: "SEK", name: "couronne suedoise" },
  { code: "SGD", name: "dollar de singapour" },
  { code: "SHP", name: "livre de sainte-helene" },
  { code: "SLE", name: "leone sierra-leonais" },
  { code: "SLL", name: "leone sierra-leonais (1964-2022)" },
  { code: "SOS", name: "shilling somalien" },
  { code: "SRD", name: "dollar surinamais" },
  { code: "SSP", name: "livre sud-soudanaise" },
  { code: "STN", name: "dobra santomeen" },
  { code: "SVC", name: "colon salvadorien" },
  { code: "SYP", name: "livre syrienne" },
  { code: "SZL", name: "lilangeni swazi" },
  { code: "THB", name: "baht thailandais" },
  { code: "TJS", name: "somoni tadjik" },
  { code: "TMT", name: "nouveau manat turkmene" },
  { code: "TND", name: "dinar tunisien" },
  { code: "TOP", name: "paanga tongan" },
  { code: "TRY", name: "livre turque" },
  { code: "TTD", name: "dollar de trinite-et-tobago" },
  { code: "TWD", name: "nouveau dollar taiwanais" },
  { code: "TZS", name: "shilling tanzanien" },
  { code: "UAH", name: "hryvnia ukrainienne" },
  { code: "UGX", name: "shilling ougandais" },
  { code: "USD", name: "dollar des etats-unis" },
  { code: "UYU", name: "peso uruguayen" },
  { code: "UZS", name: "sum ouzbek" },
  { code: "VES", name: "bolivar venezuelien" },
  { code: "VND", name: "dong vietnamien" },
  { code: "VUV", name: "vatu vanuatuan" },
  { code: "WST", name: "tala samoan" },
  { code: "XAF", name: "franc cfa (beac)" },
  { code: "XCD", name: "dollar des caraibes orientales" },
  { code: "XCG", name: "florin caribeen" },
  { code: "XDR", name: "droit de tirage special" },
  { code: "XOF", name: "franc cfa (bceao)" },
  { code: "XPF", name: "franc cfp" },
  { code: "XSU", name: "xsu" },
  { code: "YER", name: "riyal yemenite" },
  { code: "ZAR", name: "rand sud-africain" },
  { code: "ZMW", name: "kwacha zambien" },
  { code: "ZWG", name: "zwg" },
  { code: "ZWL", name: "dollar zimbabween (2009)" }
];

export function getCurrencyOptionLabel(option: CurrencyOption): string {
  return `${option.code} - ${option.name}`;
}
